src/app_beneficiario/urls.py
from django.urls import path 
from .views import listar_beneficiarios, detalle_beneficiario, crear_beneficiario

app_name = 'beneficiarios'

urlpatterns = [
    path('', listar_beneficiarios, name='listar-beneficiarios'),
    path('<int:pk>/', detalle_beneficiario, name='detalle-benefiario'),
    path('alta/', crear_beneficiario, name='crear-beneficiario')
]

src/app_beneficio/urls.py
from django.urls import path 
from .views import BeneficiosListView, BeneficiosDetailView, BeneficiosListViewActivos, alta_beneficio, sacar_vigencia

app_name = 'beneficios'

urlpatterns = [
    path('', BeneficiosListView.as_view(), name='lista-beneficio'),
    path('activos/', BeneficiosListViewActivos.as_view(), name='lista-activos'),
    path('<int:pk>/', BeneficiosDetailView.as_view(), name='detalle-beneficio'),
    path('alta/', alta_beneficio, name='alta-beneficio'),
    path('baja/<int:pk>', sacar_vigencia, name='baja-beneficio')
]

src/proj_capresca/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views 


urlpatterns = [
    path("admin/", admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path("beneficiarios/", include('app_beneficiario.urls', namespace='beneficiarios')),
    path("beneficios/", include('app_beneficio.urls', namespace='beneficios'))
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/app_beneficiario/models.py
from django.db import models 
from django.contrib.auth.models import User 

from app_beneficio.models import Beneficio 

# Create your models here.
class Beneficiario(models.Model):
    GENEROS = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('X', 'No Binario'),
        ('N', 'No Informado')
    )

    beneficio = models.ForeignKey(Beneficio, on_delete=models.CASCADE)
    creado_por = models.ForeignKey(User, on_delete=models.CASCADE)
    apellido = models.CharField(max_length=50)
    nombre = models.CharField(max_length=50)
    dni = models.PositiveIntegerField(unique=True)
    cuil = models.PositiveBigIntegerField(unique=True)
    genero = models.CharField(max_length=1, choices=GENEROS, default='N')
    imagen = models.ImageField(upload_to='beneficiarios_fotos', default='usuario.png')
    domicilio = models.CharField(max_length=100)
    alta_beneficio = models.DateTimeField()
    baja_beneficio = models.DateTimeField(null=True, blank=True)
    activo = models.BooleanField(default=False)
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)

    def __str__(self):
        return F"{self.apellido.upper()}, {self.nombre.title()} cuil {self.cuil} activo: {self.activo}"
    

    class Meta:
        ordering = ('apellido', 'nombre', 'dni')

src/app_beneficio/models.py
from django.db import models

# Create your models here.
class Beneficio(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()
    vigente = models.BooleanField(default=True)
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)

    def __str__(self):
        return F"{self.nombre} - Creado el {self.creado} Vigente: { self.vigente }"

    class Meta:
        ordering = ('-modificado', )

src/core/models.py
from django.db import models

# Create your models here.

src/app_beneficiario/forms.py
from django import forms 
from .models import Beneficiario 


class BeneficiarioForm(forms.ModelForm):
    class Meta:
        model = Beneficiario
        fields = '__all__'
        widgets = {
            'alta_beneficio': forms.SelectDateWidget(),
            'baja_beneficio': forms.SelectDateWidget()
        }

        

src/app_beneficio/forms.py
from django import forms
from .models import Beneficio

# class BeneficioForm(forms.Form):
#     nombre = forms.CharField(max_length=50)
#     descripcion = forms.CharField(max_length=150)
#     vigente = forms.BooleanField()

class BeneficioForm(forms.ModelForm):
    class Meta:
        model = Beneficio
        fields = [ 'nombre', 'descripcion', 'vigente']

src/app_beneficiario/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required
from .models import Beneficiario 
from .forms import  BeneficiarioForm 

# Create your views here.
# Vistas basadas en funciones
@login_required
@permission_required('app_beneficiario.view_beneficiario')
def listar_beneficiarios(request):

    beneficiarios = Beneficiario.objects.all()

    return render(request, 'beneficiarios/lista.html', {
        'titulo': 'Listado de beneficiarios',
        'beneficiarios': beneficiarios, 
    })

@login_required
@permission_required('app_beneficiario.view_beneficiario')
def detalle_beneficiario(request, pk):

    beneficiario = Beneficiario.objects.get(pk=pk)

    return render(request, 'beneficiarios/detalle.html', {
        'titulo': 'Detalle del beneficiario',
        'beneficiario': beneficiario
    })

@login_required
@permission_required('app_beneficiario.add_beneficiario')
def crear_beneficiario(request):

    if request.method == 'POST':
        form = BeneficiarioForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
        else:
            print(form.errors)

    form = BeneficiarioForm()

    return render(request, 'beneficiarios/alta.html', {
        'titulo': 'Alta de beneficiarios',
        'form': form
    })

src/app_beneficio/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from django.contrib.auth.views import LoginView

from .models import Beneficio
from .forms import BeneficioForm

# Create your views here.
class BeneficiosListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    model = Beneficio
    #queryset = Beneficio.objects.filter(vigente=True)
    permission_required = 'app_beneficio.view_beneficio'
    template_name = 'beneficios/lista.html'

class BeneficiosListViewActivos(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    #model = Beneficio
    queryset = Beneficio.objects.filter(vigente=True)
    permission_required = [ 'app_beneficio.view_beneficio',]
    template_name = 'beneficios/lista.html'

class BeneficiosListViewInactivos(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    #model = Beneficio
    queryset = Beneficio.objects.filter(vigente=False)
    permission_required = [ 'app_beneficio.view_beneficio',]
    template_name = 'beneficios/lista.html'

class BeneficiosDetailView(LoginRequiredMixin, DetailView):
    model = Beneficio
    template_name = 'beneficios/detalle.html'

@login_required
def alta_beneficio(request):

    if request.method == 'POST':

        form = BeneficioForm(data=request.POST)

        if form.is_valid():
            form.save()

    
    form = BeneficioForm()

    return render(request, 'beneficios/alta.html', {
        'form': form
    })


@login_required
def sacar_vigencia(request, pk):

    beneficio = Beneficio.objects.get(pk=pk)
    beneficio.vigente = False
    beneficio.save()

    return redirect('')

src/core/views.py
from django.shortcuts import render

# Create your views here.

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="es">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CAPRESCA | {% block title %}{% endblock %} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <ul class="nav justify-content-center">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="https://capresca.gob.ar/">
            <img src="{% static 'imagenes/capresca-logo-2021-2.png'%}" width="200px" alt="Logo Capresca" />
          </a>
        </li>

        {% if request.user.is_authenticated %}

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Beneficiarios</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Beneficios</a>
        </li>
        <li class="nav-item">
          <a class="nav-link">Reportes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link">Acerca de...</a>
        </li>

      {% endif %}

      </ul>



        {% block container %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
  </body>

</html>

src/templates/beneficiarios/alta.html
{% extends 'base.html' %}

{% block title %}
{{ titulo }}
{% endblock title %}

{% block container %}
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_div }}
    <button type="submit">Grabar!!</button>
</form>
{% endblock container %}

src/templates/beneficiarios/detalle.html
{% extends 'base.html' %}

{% block title %}
    {{ titulo }}
{% endblock %}

{% block container %}

<div class="card" style="width: 18rem;">
    <img src="{{ beneficiario.imagen.url }}" class="card-img-top" alt="foto de perfil">
    <div class="card-body">
      <h5 class="card-title">Beneficiario id: {{ beneficiario.id }}</h5>
      <h3 class="card-title">Apellido y nombre: {{ beneficiario.apellido }} {{ beneficiario.nombre }}</h3>
      <p class="card-text">{{ benefiario.domicilio }}</p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">{{ beneficiario.dni }}</li>
      <li class="list-group-item">{{ beneficiario.cuil }}</li>
      <li class="list-group-item">{{ beneficiario.genero }}</li>
    </ul>
    <div class="card-body">
      <a href="#" class="card-link">Card link</a>
      <a href="#" class="card-link">Another link</a>
    </div>
  </div>



{% endblock %}

src/templates/beneficiarios/lista.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ titulo }}
{% endblock %}

{% block container %}

<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Foto Perfil</th>
        <th scope="col">Apellido</th>
        <th scope="col">Nombre</th>
        <th scope="col">Dirección</th>
        <th scope="col">Género</th>
        <th scope="col">CUIL</th>
        <th scope="col">Activo</th>
      </tr>
    </thead>
    <tbody>
    {% for beneficiario in beneficiarios %}
      <tr>
        <th scope="row">
          <a href="{% url 'beneficiarios:detalle-benefiario' beneficiario.id %}">
            {{ beneficiario.id }}
          </a>
        </th>
        <td><img src="{{ beneficiario.imagen.url }}" width="50px" alt="Imagen de perfil del Beneficiario"></td>
        <td>{{ beneficiario.apellido }}</td>
        <td>{{ beneficiario.nombre }}</td>
        <td>{{ beneficiario.domicilio }}</td>
        <td>{{ beneficiario.genero }}</td>
        <td>{{ beneficiario.cuil }}</td>


        {% if beneficiario.activo  %}
            <td><img src="{% static 'imagenes/activo.png' %}" width="50px" alt="Activo"></td>
        {% else %}
            <td><img src="{% static 'imagenes/inactivo.png' %}" width="50px" alt="Inactivo"></td>
        {% endif %}


      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock %}

src/templates/beneficios/alta.html
{% extends 'base.html' %}

{% block container %}

<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_div }}

    <button type="submit">Grabar</button>
</form>

{% endblock %}

src/templates/beneficios/detalle.html
{% extends 'base.html' %}

{% block title %}
    {{ titulo }}
{% endblock %}

{% block container %}

{{ beneficio }}

{% endblock %}

src/templates/beneficios/lista.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ titulo }}
{% endblock %}

{% block container %}

<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Nombre del beneficio</th>
        <th scope="col">Activo</th>
      </tr>
    </thead>
    <tbody>
    {% for beneficio in object_list %}
      <tr>
        <th scope="row">
          <a href="{% url 'beneficios:detalle-beneficio' beneficio.id %}">
            {{ beneficio.id }}
          </a>
        </th>
        <td>{{ beneficio.nombre }}</td>



        {% if beneficio.activo  %}
            <td><img src="{% static 'imagenes/activo.png' %}" width="50px" alt="Activo"></td>
        {% else %}
            <td><img src="{% static 'imagenes/inactivo.png' %}" width="50px" alt="Inactivo"></td>
        {% endif %}


      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock %}